version: ‘3’ # version of docker-compose
services: # defining service/s
  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=spring_demo
    ports:
      - 3307:3306
    networks:
      - network_1
  backend:
    image: spring-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db:3306/spring_demo # overwrite configuration from application.properties file
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - network_1
  nginx:
    image: nginx-with-angular
    ports:
      - 80:80
    networks:
      - network_1

networks:
  network_1:
